baseURL = 'https://41147035s.github.io'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "PaperMod"
buildDrafts = false

# topic: menu bar
## subtopic: tags
[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags/"
weight = 10

[[menu.main]]
identifier = "categories"
name = "categories"
url = "/categories/"
weight = 20

[[menu.main]]
identifier = "archives"
name = "archives"
url = "/archives/"
weight = 30

[params.profileMode]
enabled = true
title = "Hello, World"

[[params.socialIcons]]
name = "youtube"
url = "https://www.youtube.com/watch?v=KM7r1z8FxUw"